#####################
# GENERAL USER INFO #
#####################

# Grid search markup:
#   This main config will be split up in k individual run configs based on list markup [...].
#   If a single list itself is one argument and should not be splitted, a second list has to be wrapped around it.
#   Example:
#     layers: [256, 128, 64]                  -> will be splitted into individual arguments
#     layers: [[256, 128, 64]]                -> will be kept as one argument
#     layers: [[256, 128, 64], [256, 64, 32]] -> will be splitted into two arguments, both being a list


#####################
# CONFIG            #
#####################

out_dir: '/data/text_dedicom/experiments/'

wiki_articles: [['Donald Trump', 'New York City', 'Shark'],
                ['Donald Trump', 'New York City', 'Michael Bloomberg'],
                ['Shark', 'Dolphin', 'Whale'],
                ['Shark', 'Bee', 'Elephant'],
                ['Germany', 'Belgium', 'France'],
                ['Soccer', 'Tennis', 'Rugby football'],
                ['Soccer', 'Tennis', 'Boxing'],
                ['Brad Pitt', 'Leonardo Dicaprio', 'Rafael Nadal'],
                ['Apple (company)', 'Google', 'Amazon (company)'],
                ['Apple (company)', 'Google', 'Walmart'],
                ['Soccer', 'Bee', 'Johnny Depp'],
                ['Tennis', 'Dolphin', 'New York City']]

matrix_type: 'ppmi'
window_size: 7
a_constraint: 'col_scaled_row_softmax'
preprocessing: [['add_whitespace_after_period',
                 'to_lower',
                 'remove_stopwords',
                 'remove_punctuation',
                 'remove_digits',
                 'remove_single_chars',
                 'remove_multi_spaces']]
k: [3, 6, 9]
seed: 42
lr_a: 0.001
lr_r: 0.01
num_epochs: 15000
evaluate_every: 500
